### ISSUE TITLE
Files missing in Crackle Generator

### ISSUE THREAD

**Issue by dieterrosch** [VincentRisi/jportal#2]
There are  files missing in the crackle generator. It complains about ParseException.java not being there. Also some Simple* classes

**Comment by VincentRisi** [comment]
Those are generated using javacc - check out the readme it may have the
note on javacc (parser generator).

**Comment by VincentRisi** [comment]
javacc - SF JavaCC Eclipse Plug-in feature 1.5.32
sf.eclipse.javacc.feature.feature.group Rémi Koutcherawy

**Comment by dieterrosch** [comment]
Works now. Closing the issue.
